language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install: composer install

notifications:
  email: false

script: 
  - cd tests
  - php run.php

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.3
    - php: 7.0
