language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install: composer install

notifications:
  email: false

script:
  - cd tests
  - php run.php --coverage=clover

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.3

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml
