name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: PHP ${{ matrix.php-versions }} ${{ matrix.composer-args }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4']
        composer-args: ['', '--prefer-lowest']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, apcu
          ini-values: apc.enable_cli=1
          coverage: xdebug
      - name: Install Dependencies
        run: |
          composer update --no-progress --no-suggest --prefer-stable --optimize-autoloader ${{ matrix.composer-args }}
      - name: Static Analysis
        run: composer static-analysis
      - name: Code Style Check
        run: composer style-check
      - name: Test
        run: composer test-with-coverage
      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash) -f tests/coverage/clover.xml
  roave_bc_check:
    name: Roave BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
